# Generated by Django 5.1 on 2025-06-08 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Surname')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_specified', 'Rather not to specify')], max_length=15, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('personality_trait', models.CharField(choices=[('brave', 'Brave (勇敢)'), ('kind', 'Kind (善良)'), ('artistic', 'Artistic (文艺)'), ('calm', 'Calm (平静)'), ('cheerful', 'Cheerful (开朗)'), ('wise', 'Wise (智慧)'), ('gentle', 'Gentle (温和)'), ('strong', 'Strong (坚强)'), ('creative', 'Creative (创意)'), ('loyal', 'Loyal (忠诚)')], max_length=20, verbose_name='Personality Trait')),
                ('preferred_style', models.CharField(choices=[('traditional', 'Traditional/Classical'), ('artistic', 'Artistic/Poetic'), ('modern', 'Modern/Cool'), ('professional', 'Professional/Formal')], max_length=20, verbose_name='Preferred Style')),
                ('generated_chinese_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Generated Chinese Name')),
                ('name_pinyin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name Pinyin')),
                ('name_meaning', models.TextField(blank=True, null=True, verbose_name='Name Meaning')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Name Generation Request',
                'verbose_name_plural': 'Name Generation Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
