# Generated by Django 5.1 on 2025-06-12 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namegen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('page_visits', models.IntegerField(default=0, verbose_name='页面访问数')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='独立访客数')),
                ('unique_ips', models.IntegerField(default=0, verbose_name='独立IP数')),
                ('name_generations', models.IntegerField(default=0, verbose_name='姓名生成数')),
                ('name_card_generations', models.IntegerField(default=0, verbose_name='名片生成数')),
                ('tts_requests', models.IntegerField(default=0, verbose_name='语音合成请求数')),
                ('share_clicks', models.IntegerField(default=0, verbose_name='分享点击数')),
                ('country_stats', models.JSONField(blank=True, default=dict, verbose_name='国家统计')),
                ('city_stats', models.JSONField(blank=True, default=dict, verbose_name='城市统计')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageVisitStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('page_visit', '页面访问'), ('name_generation', '姓名生成'), ('name_card_generation', '名片生成'), ('tts_request', '语音合成'), ('share_click', '分享点击'), ('result_view', '结果查看')], max_length=20, verbose_name='活动类型')),
                ('page_url', models.URLField(blank=True, null=True, verbose_name='页面URL')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('generated_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='生成的姓名')),
                ('request_id', models.IntegerField(blank=True, null=True, verbose_name='关联请求ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='会话密钥')),
                ('share_platform', models.CharField(blank=True, max_length=20, null=True, verbose_name='分享平台')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(秒)')),
            ],
            options={
                'verbose_name': '页面访问统计',
                'verbose_name_plural': '页面访问统计',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity_type', 'created_at'], name='namegen_pag_activit_8c60f2_idx'), models.Index(fields=['ip_address', 'created_at'], name='namegen_pag_ip_addr_a76cb1_idx'), models.Index(fields=['created_at'], name='namegen_pag_created_a830c3_idx')],
            },
        ),
    ]
