# Generated by Django 5.1 on 2024-09-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="color",
            field=models.CharField(default="null", max_length=7),
        ),
    ]
