# Generated by Django 5.1 on 2025-05-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_feature_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['category', 'order']},
        ),
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.CharField(choices=[('typing', '汉字输入'), ('reading', '阅读理解'), ('listening', '听力练习'), ('speaking', '口语练习'), ('other', '其他工具')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.CharField(default='fas fa-star', help_text='Font Awesome 图标类名', max_length=50),
        ),
    ]
