# Generated by Django 5.1 on 2024-09-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="status",
        ),
        migrations.AddField(
            model_name="assignmentset",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
