# Generated by Django 5.1 on 2024-09-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_question_status_assignmentset_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
    ]
