# Generated by Django 5.1 on 2025-07-29 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak_practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': '聊天消息 (Chat Message)', 'verbose_name_plural': '聊天消息 (Chat Messages)'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at'], 'verbose_name': '聊天会话 (Chat Session)', 'verbose_name_plural': '聊天会话 (Chat Sessions)'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='audio_duration',
            field=models.FloatField(blank=True, help_text='音频时长（秒）(Audio duration in seconds)', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='input_method',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('translation', 'Translation')], default='text', help_text='消息输入方式 (Message input method)', max_length=11),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间 (Created At)'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='scene',
            field=models.TextField(verbose_name='场景 (Scene)'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户 (User)'),
        ),
    ]
