# Generated by Django 5.1 on 2025-07-29 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak_practice', '0002_alter_chatmessage_options_alter_chatsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='speak_pract_session_e2db0c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender_type', 'timestamp'], name='speak_pract_sender__225c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['input_method', 'timestamp'], name='speak_pract_input_m_144a43_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['-timestamp'], name='speak_pract_timesta_22a40a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-created_at'], name='speak_pract_user_id_6f8d18_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['-created_at'], name='speak_pract_created_b2ff3a_idx'),
        ),
    ]
