# Generated by Django 5.1 on 2026-03-08 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak_practice', '0003_chatmessage_speak_pract_session_e2db0c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSceneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题 (Title)')),
                ('description', models.TextField(verbose_name='描述 (Description)')),
                ('scene_prompt', models.TextField(verbose_name='场景提示词 (Scene Prompt)')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='难度 (Level)')),
                ('icon', models.CharField(default='fas fa-comments', max_length=50, verbose_name='图标 (Icon)')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类 (Category)')),
                ('target_profile', models.TextField(blank=True, verbose_name='适用背景 (Target Profile)')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='关键词 (Keywords)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用 (Active)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序 (Sort Order)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间 (Created At)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间 (Updated At)')),
            ],
            options={
                'verbose_name': '口语场景模板 (Practice Scene Template)',
                'verbose_name_plural': '口语场景模板 (Practice Scene Templates)',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserSceneExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_title', models.CharField(blank=True, max_length=120)),
                ('scene_text', models.TextField()),
                ('scene_signature', models.CharField(max_length=40)),
                ('scene_source', models.CharField(choices=[('custom', 'Custom'), ('template', 'Template'), ('ai_generated', 'AI Generated'), ('fallback', 'Fallback'), ('emergency_fallback', 'Emergency Fallback')], default='custom', max_length=20)),
                ('exposure_type', models.CharField(choices=[('shown', 'Shown'), ('selected', 'Selected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户场景记录 (User Scene Exposure)',
                'verbose_name_plural': '用户场景记录 (User Scene Exposures)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='scene_signature',
            field=models.CharField(blank=True, max_length=40, verbose_name='场景签名 (Scene Signature)'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='scene_source',
            field=models.CharField(choices=[('custom', 'Custom'), ('template', 'Template'), ('ai_generated', 'AI Generated'), ('fallback', 'Fallback'), ('emergency_fallback', 'Emergency Fallback')], default='custom', max_length=20, verbose_name='场景来源 (Scene Source)'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='scene_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='speak_practice.practicescenetemplate', verbose_name='场景模板 (Scene Template)'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'scene_signature'], name='speak_pract_user_id_a09ab5_idx'),
        ),
        migrations.AddField(
            model_name='usersceneexposure',
            name='scene_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exposures', to='speak_practice.practicescenetemplate'),
        ),
        migrations.AddField(
            model_name='usersceneexposure',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_exposures', to='speak_practice.chatsession'),
        ),
        migrations.AddField(
            model_name='usersceneexposure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_exposures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersceneexposure',
            index=models.Index(fields=['user', '-created_at'], name='speak_pract_user_id_61cab7_idx'),
        ),
        migrations.AddIndex(
            model_name='usersceneexposure',
            index=models.Index(fields=['user', 'scene_signature'], name='speak_pract_user_id_57244e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersceneexposure',
            index=models.Index(fields=['exposure_type', '-created_at'], name='speak_pract_exposur_2fcba1_idx'),
        ),
    ]
