"""
Django settings for tongcove project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import platform
from dotenv import load_dotenv, dotenv_values
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(override=True)

# Load environment variables
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
GOOGLE_APPLICATION_CREDENTIALS = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS')
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY')



DASHBOARD_COLORS = [
    '#99E7C5',
    '#B5B0F6',
    '#EDA3A3',
    '#F4CB9B'
]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 从环境变量读取，绝不硬编码在源码里 —— 提交进 git 的密钥会让任何人伪造 session / 签名 cookie / CSRF token
# (Read from the environment; never hardcode. A committed key lets anyone forge sessions / CSRF tokens.)
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# 本地开发是 macOS，生产是 Linux VM —— 因此 macOS 上自动开启 DEBUG，Linux 默认关闭。
# 也可用 DEBUG 环境变量显式覆盖（DEBUG=true / DEBUG=false）。
# 生产环境绝不能以 DEBUG=True 运行：会泄露完整 traceback / settings，并使下方的生产加固块失效。
# (Local dev is macOS, production is a Linux VM; DEBUG auto-on for macOS, off for Linux. Override via DEBUG env var.)
_debug_env = os.environ.get('DEBUG', '').strip().lower()
if _debug_env in ('true', '1', 'yes'):
    DEBUG = True
elif _debug_env in ('false', '0', 'no'):
    DEBUG = False
else:
    DEBUG = platform.system() == 'Darwin'

if not SECRET_KEY:
    if DEBUG:
        # 仅开发期回退，DEBUG=False 时绝不会用到 (Dev-only fallback; never used in production.)
        SECRET_KEY = 'django-insecure-dev-only-key-do-not-use-in-production'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY environment variable is required when DEBUG is False'
        )

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'afterclass.learnchineseperth.com.au']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'accounts',
    'chatbots',
    'dashboard',
    'assignments',
    'stories',
    'pinyinit',
    'typingchinese',
    'namegen',
    'speak_practice',
    # 'ckeditor',
    'ckeditor_uploader',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "namegen.middleware.StatisticsMiddleware",
]

ROOT_URLCONF = "tongcove.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tongcove.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Login redirect configuration
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'accounts.backends.CaseInsensitiveModelBackend',  # Custom case-insensitive backend
    'django.contrib.auth.backends.ModelBackend',     # Default backend as fallback
]

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload'],
        'upload': {
            'types': ['png', 'jpg', 'jpeg', 'gif', 'webp'],
        }
    },
}

ALLOWED_UPLOAD_IMAGES = ['png', 'jpg', 'jpeg', 'gif', 'webp']

CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'namegen_statistics.log'),
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'namegen.statistics': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'namegen.middleware': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# 缓存配置 (Cache configuration)
# 使用数据库缓存表（DatabaseCache）而非 LocMemCache：
#   - LocMemCache 是每进程独立的，多 worker（gunicorn）部署下限流计数互不可见 →
#     实际限额变成 配置值 × worker 数，且重启即丢；
#   - 大体积的 TTS base64 音频在 MAX_ENTRIES=1000 的内存缓存里会被快速逐出、命中率极低，
#     且每个 worker 各存一份占内存。
# 改为 DatabaseCache 后：限流计数、TTS/翻译缓存、IP 地理缓存在所有 worker 间一致且持久。
# 表通过 migration speak_practice/0005 由 createcachetable 创建。
# (DatabaseCache gives cross-worker-consistent rate limiting + persistent audio cache.)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'afterclass_cache',  # 数据库缓存表名 (DB cache table name)
        'TIMEOUT': 300,  # 默认 5 分钟 (default 5 minutes)
        'OPTIONS': {
            # 提高上限，避免大体积 TTS 音频被频繁逐出（24h TTL 的音频应能留存）
            # (Higher cap so large TTS audio entries are not constantly culled.)
            'MAX_ENTRIES': 10000,
            'CULL_FREQUENCY': 4,
        }
    }
}

# Security Configuration
# 安全配置 (Security Configuration)

# Rate Limiting Settings
CHAT_API_RATE_LIMIT = int(os.environ.get('CHAT_API_RATE_LIMIT', 30))
AUDIO_API_RATE_LIMIT = int(os.environ.get('AUDIO_API_RATE_LIMIT', 10))
TRANSLATE_API_RATE_LIMIT = int(os.environ.get('TRANSLATE_API_RATE_LIMIT', 20))

# Audio Security Settings
AUDIO_MAX_FILE_SIZE = int(os.environ.get('AUDIO_MAX_FILE_SIZE', 10 * 1024 * 1024))  # 10MB
AUDIO_MAX_DURATION = int(os.environ.get('AUDIO_MAX_DURATION', 300))  # 5 minutes
AUDIO_MALWARE_SCAN_ENABLED = os.environ.get('AUDIO_MALWARE_SCAN_ENABLED', 'True').lower() == 'true'

# Input Validation Settings
INPUT_MAX_TEXT_LENGTH = int(os.environ.get('INPUT_MAX_TEXT_LENGTH', 1000))
INPUT_STRICT_VALIDATION = os.environ.get('INPUT_STRICT_VALIDATION', 'True').lower() == 'true'

# Security Logging Settings
SECURITY_LOG_RATE_LIMITS = os.environ.get('SECURITY_LOG_RATE_LIMITS', 'True').lower() == 'true'
SECURITY_LOG_MALICIOUS_UPLOADS = os.environ.get('SECURITY_LOG_MALICIOUS_UPLOADS', 'True').lower() == 'true'
SECURITY_ALERT_THRESHOLD = int(os.environ.get('SECURITY_ALERT_THRESHOLD', 10))

# Session Security
SESSION_TIMEOUT_MINUTES = int(os.environ.get('SESSION_TIMEOUT_MINUTES', 30))
MAX_SESSIONS_PER_USER = int(os.environ.get('MAX_SESSIONS_PER_USER', 5))

# CSRF Protection
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Production Security Settings (only apply in production)
if not DEBUG:
    # 站点位于 nginx/Cloudflare 之后（由它们终止 TLS）。让 Django 信任 X-Forwarded-Proto，
    # 使 request.is_secure() 正确、SSL 重定向不会死循环（需代理设置该头，nginx/Cloudflare 默认会）。
    # (Behind nginx/Cloudflare TLS termination; trust X-Forwarded-Proto to avoid redirect loops.)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # 可通过环境变量关闭，以防代理链是纯 HTTP 时产生重定向死循环
    # (Toggleable in case the proxy chain is HTTP-only.)
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
